# - setup:
#   register: my_setup
# - debug:
#     msg: "{{ my_setup }}"

- name: Find all files
  find:
    path: "{{ inv_folder }}"
  register: list_of_files

- name: set_fact - basename all files  
  set_fact:
    files: "{{ list_of_files.files|
               json_query('[].path')|
               map('basename')|
               list }}"               

- name: stat files from set_fact
  stat:
    path: "{{ inv_folder }}/{{ item }}"
  loop: "{{ files }}"
  register: status_of_files

- name: set_fact for master_list
  set_fact:
    master_list: "{{ hostvars[master].status_of_files.results|
                     json_query('[].{item: item, hash: stat.checksum}') }}"

- name: DEBUG - set_fact for master_list                     
  debug:
    msg: "{{ master_list|
             symmetric_difference(hostvars[item_host].status_of_files.results|
             json_query('[].{item: item, hash: stat.checksum}')) }}"
  loop: "{{ groups['all'] | difference([ master ]) }}"
  loop_control:
    loop_var: item_host            
